UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Buriti Alegre') WHERE pe.nr_cep = '75664970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'São Paulo') WHERE pe.nr_cep = '05350901';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Erechim') WHERE pe.nr_cep = '99704046';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Osasco') WHERE pe.nr_cep = '06029900';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Brasília') WHERE pe.nr_cep = '70092900';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Panamá') WHERE pe.nr_cep = '75599970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Tupaciguara') WHERE pe.nr_cep = '38480000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Tupaciguara') WHERE pe.nr_cep = '38480000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Tupaciguara') WHERE pe.nr_cep = '38480000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'São Paulo') WHERE pe.nr_cep = '01046925';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Tupaciguara') WHERE pe.nr_cep = '38480000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Monte Alegre de Minas') WHERE pe.nr_cep = '38475000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Monte Alegre de Minas') WHERE pe.nr_cep = '38475000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'São Paulo') WHERE pe.nr_cep = '05093901';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Magé') WHERE pe.nr_cep = '25931970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Itapecerica da Serra') WHERE pe.nr_cep = '06886990';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Caçador') WHERE pe.nr_cep = '89510000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Tupaciguara') WHERE pe.nr_cep = '38480000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Concórdia') WHERE pe.nr_cep = '89712054';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Monte Alegre de Minas') WHERE pe.nr_cep = '38475000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Balneário Camboriú') WHERE pe.nr_cep = '88338900';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'São Pedro da Aldeia') WHERE pe.nr_cep = '28948890';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Brasília') WHERE pe.nr_cep = '71608971';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Miracema do Tocantins') WHERE pe.nr_cep = '77654970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Miracema do Tocantins') WHERE pe.nr_cep = '77654970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Miracema do Tocantins') WHERE pe.nr_cep = '77654970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Theobroma') WHERE pe.nr_cep = '76866970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Tupaciguara') WHERE pe.nr_cep = '38480000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Tupaciguara') WHERE pe.nr_cep = '38480000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Tupaciguara') WHERE pe.nr_cep = '38480000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Tupaciguara') WHERE pe.nr_cep = '38480000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Tupaciguara') WHERE pe.nr_cep = '38480000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Tupaciguara') WHERE pe.nr_cep = '38480000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Concórdia') WHERE pe.nr_cep = '89712060';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Concórdia') WHERE pe.nr_cep = '89712060';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Santa Helena de Goiás') WHERE pe.nr_cep = '75924970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Brasília') WHERE pe.nr_cep = '72701994';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Cotia') WHERE pe.nr_cep = '06700999';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Charco (Castro)') WHERE pe.nr_cep = '84195000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Aloândia') WHERE pe.nr_cep = '75619970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Uberlândia') WHERE pe.nr_cep = '38425528';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Concórdia') WHERE pe.nr_cep = '89712060';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'São Pedro da Aldeia') WHERE pe.nr_cep = '28946195';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Concórdia') WHERE pe.nr_cep = '89712054';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Itapecerica da Serra') WHERE pe.nr_cep = '06886990';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Uberlândia') WHERE pe.nr_cep = '38425385';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Concórdia') WHERE pe.nr_cep = '89712062';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Cacoal') WHERE pe.nr_cep = '76960970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Itapecerica da Serra') WHERE pe.nr_cep = '06850999';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Panamá') WHERE pe.nr_cep = '75599970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'São Paulo') WHERE pe.nr_cep = '05350901';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'São Paulo') WHERE pe.nr_cep = '05350901';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Brasília') WHERE pe.nr_cep = '72600970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'São Paulo') WHERE pe.nr_cep = '05350901';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Pedro Leopoldo') WHERE pe.nr_cep = '33256000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Turvelândia') WHERE pe.nr_cep = '75979970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Juquitiba') WHERE pe.nr_cep = '06950972';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Uberlândia') WHERE pe.nr_cep = '38425467';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'São Paulo') WHERE pe.nr_cep = '01419909';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Concórdia') WHERE pe.nr_cep = '89707044';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Curitiba') WHERE pe.nr_cep = '81690901';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Concórdia') WHERE pe.nr_cep = '89700083';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'São Paulo') WHERE pe.nr_cep = '05423901';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'São Paulo') WHERE pe.nr_cep = '05423905';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'São Paulo') WHERE pe.nr_cep = '01009903';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'São Pedro da Aldeia') WHERE pe.nr_cep = '28948129';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Panamá') WHERE pe.nr_cep = '75599970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Fazenda Rio Grande') WHERE pe.nr_cep = '83823275';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Concórdia') WHERE pe.nr_cep = '89712050';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Uberlândia') WHERE pe.nr_cep = '38425500';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Caçador') WHERE pe.nr_cep = '89510000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Caçador') WHERE pe.nr_cep = '89510000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Concórdia') WHERE pe.nr_cep = '89712056';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Uberlândia') WHERE pe.nr_cep = '38425566';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Tupaciguara') WHERE pe.nr_cep = '38480000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Joviânia') WHERE pe.nr_cep = '75614970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Tupaciguara') WHERE pe.nr_cep = '38480000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Tupaciguara') WHERE pe.nr_cep = '38480000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Tupaciguara') WHERE pe.nr_cep = '38480000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Tupaciguara') WHERE pe.nr_cep = '38480000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Monte Alegre de Minas') WHERE pe.nr_cep = '38475000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Tupaciguara') WHERE pe.nr_cep = '38480000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Buriti Alegre') WHERE pe.nr_cep = '75664970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Buriti Alegre') WHERE pe.nr_cep = '75664970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Concórdia') WHERE pe.nr_cep = '89712084';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'São Paulo') WHERE pe.nr_cep = '02941010';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Uberlândia') WHERE pe.nr_cep = '38425477';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Uberlândia') WHERE pe.nr_cep = '38425464';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Uberlândia') WHERE pe.nr_cep = '38425455';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Senador Canedo') WHERE pe.nr_cep = '75262268';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Trindade') WHERE pe.nr_cep = '75383129';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Embu das Artes') WHERE pe.nr_cep = '06803971';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Panamá') WHERE pe.nr_cep = '75599970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Santa Helena de Goiás') WHERE pe.nr_cep = '75924970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Brasília') WHERE pe.nr_cep = '71950904';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Santo Antônio do Descoberto') WHERE pe.nr_cep = '72902040';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Nossa Senhora dos Navegantes (Faxinalzinho)') WHERE pe.nr_cep = '99657000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Eunápolis') WHERE pe.nr_cep = '45829004';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Nova Lima') WHERE pe.nr_cep = '34007970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Rio de Janeiro') WHERE pe.nr_cep = '20211903';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'São Paulo') WHERE pe.nr_cep = '05350901';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Panamá') WHERE pe.nr_cep = '75599970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Tupaciguara') WHERE pe.nr_cep = '38480000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Aloândia') WHERE pe.nr_cep = '75619970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Panamá') WHERE pe.nr_cep = '75599970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'São Paulo') WHERE pe.nr_cep = '05451900';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'São Paulo') WHERE pe.nr_cep = '05350901';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Concórdia') WHERE pe.nr_cep = '89712072';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Erechim') WHERE pe.nr_cep = '99709910';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Tupaciguara') WHERE pe.nr_cep = '38480000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Tupaciguara') WHERE pe.nr_cep = '38480000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Brasília') WHERE pe.nr_cep = '72305970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Monte Alegre de Minas') WHERE pe.nr_cep = '38475000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Tupaciguara') WHERE pe.nr_cep = '38480000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Tupaciguara') WHERE pe.nr_cep = '38480000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Charco (Castro)') WHERE pe.nr_cep = '84195000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Concórdia') WHERE pe.nr_cep = '89712226';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Brasília') WHERE pe.nr_cep = '71608971';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'São Paulo') WHERE pe.nr_cep = '04618916';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Aloândia') WHERE pe.nr_cep = '75619970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Jaru') WHERE pe.nr_cep = '76890970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Sapiranga') WHERE pe.nr_cep = '93822086';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Miracema do Tocantins') WHERE pe.nr_cep = '77654970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Uberlândia') WHERE pe.nr_cep = '38425552';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Mara Rosa') WHERE pe.nr_cep = '76492970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Brasília') WHERE pe.nr_cep = '72305970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Brasília') WHERE pe.nr_cep = '72305970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Erechim') WHERE pe.nr_cep = '99702026';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Panamá') WHERE pe.nr_cep = '75599970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'São Paulo') WHERE pe.nr_cep = '05350901';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'São Paulo') WHERE pe.nr_cep = '04559909';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Osasco') WHERE pe.nr_cep = '06266990';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Brasília') WHERE pe.nr_cep = '71010970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Brasília') WHERE pe.nr_cep = '72705970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Trindade') WHERE pe.nr_cep = '75391273';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Uberlândia') WHERE pe.nr_cep = '38425450';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Cabo Frio') WHERE pe.nr_cep = '28928668';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'São Paulo') WHERE pe.nr_cep = '01311936';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'São Paulo') WHERE pe.nr_cep = '01310915';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Nova Lima') WHERE pe.nr_cep = '34007970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Tupaciguara') WHERE pe.nr_cep = '38480000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'São Paulo') WHERE pe.nr_cep = '05573900';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Tupaciguara') WHERE pe.nr_cep = '38480000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Tupaciguara') WHERE pe.nr_cep = '38480000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Tupaciguara') WHERE pe.nr_cep = '38480000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Concórdia') WHERE pe.nr_cep = '89712056';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Brasília') WHERE pe.nr_cep = '72600970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Joviânia') WHERE pe.nr_cep = '75614970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Concórdia') WHERE pe.nr_cep = '89712224';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Tupaciguara') WHERE pe.nr_cep = '38480000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Tupaciguara') WHERE pe.nr_cep = '38480000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Tupaciguara') WHERE pe.nr_cep = '38480000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Panamá') WHERE pe.nr_cep = '75599970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Concórdia') WHERE pe.nr_cep = '89712160';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'São Lourenço da Serra') WHERE pe.nr_cep = '06890970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Uberlândia') WHERE pe.nr_cep = '38425427';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'São Paulo') WHERE pe.nr_cep = '01043907';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'São Paulo') WHERE pe.nr_cep = '04602904';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Uberlândia') WHERE pe.nr_cep = '38425376';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Brasília') WHERE pe.nr_cep = '71570900';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Brasília') WHERE pe.nr_cep = '72225971';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Panamá') WHERE pe.nr_cep = '75599970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'São Paulo') WHERE pe.nr_cep = '04674901';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Brasília') WHERE pe.nr_cep = '71608900';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Tupaciguara') WHERE pe.nr_cep = '38480972';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Cacoal') WHERE pe.nr_cep = '76960970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Brasília') WHERE pe.nr_cep = '72305970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Pouso Alegre') WHERE pe.nr_cep = '37555000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Concórdia') WHERE pe.nr_cep = '89712050';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Trindade') WHERE pe.nr_cep = '75392706';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Tupaciguara') WHERE pe.nr_cep = '38480970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Brasília') WHERE pe.nr_cep = '73105909';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Brasília') WHERE pe.nr_cep = '70070936';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Rio Verde') WHERE pe.nr_cep = '75905900';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Tupaciguara') WHERE pe.nr_cep = '38480000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Panamá') WHERE pe.nr_cep = '75599970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Uberlândia') WHERE pe.nr_cep = '38425428';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Uberlândia') WHERE pe.nr_cep = '38425427';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Panamá') WHERE pe.nr_cep = '75599970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Sapiranga') WHERE pe.nr_cep = '93805770';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Tupaciguara') WHERE pe.nr_cep = '38480000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Uberlândia') WHERE pe.nr_cep = '38425588';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Tupaciguara') WHERE pe.nr_cep = '38480000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Tupaciguara') WHERE pe.nr_cep = '38480000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Tupaciguara') WHERE pe.nr_cep = '38480000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Uberlândia') WHERE pe.nr_cep = '38425381';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Monte Alegre de Minas') WHERE pe.nr_cep = '38475000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'São Paulo') WHERE pe.nr_cep = '05001900';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Concórdia') WHERE pe.nr_cep = '89712114';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Santana do Paraíso') WHERE pe.nr_cep = '35179000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'São Paulo') WHERE pe.nr_cep = '05361000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Embu das Artes') WHERE pe.nr_cep = '06816900';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Uberlândia') WHERE pe.nr_cep = '38425426';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Campinorte') WHERE pe.nr_cep = '76419970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Uberlândia') WHERE pe.nr_cep = '38425496';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Panamá') WHERE pe.nr_cep = '75599970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Brasília') WHERE pe.nr_cep = '72580900';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'São Paulo') WHERE pe.nr_cep = '05072901';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Santo Antônio do Descoberto') WHERE pe.nr_cep = '72902260';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Tupaciguara') WHERE pe.nr_cep = '38480000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Uberlândia') WHERE pe.nr_cep = '38425597';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Erechim') WHERE pe.nr_cep = '99700970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Vicentinópolis') WHERE pe.nr_cep = '75559970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Biguaçu') WHERE pe.nr_cep = '88162243';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Buriti Alegre') WHERE pe.nr_cep = '75664970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Turvelândia') WHERE pe.nr_cep = '75979970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'São Bernardo do Campo') WHERE pe.nr_cep = '09780900';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Caçador') WHERE pe.nr_cep = '89510000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Tupaciguara') WHERE pe.nr_cep = '38480000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Tupaciguara') WHERE pe.nr_cep = '38480000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Buriti Alegre') WHERE pe.nr_cep = '75664970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Monte Alegre de Minas') WHERE pe.nr_cep = '38475000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Tupaciguara') WHERE pe.nr_cep = '38480000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Tupaciguara') WHERE pe.nr_cep = '38480000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Tupaciguara') WHERE pe.nr_cep = '38480000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Concórdia') WHERE pe.nr_cep = '89712058';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Caçador') WHERE pe.nr_cep = '89510000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Caçador') WHERE pe.nr_cep = '89510000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Tupaciguara') WHERE pe.nr_cep = '38480000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Joviânia') WHERE pe.nr_cep = '75614970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Uberlândia') WHERE pe.nr_cep = '38425588';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'São Paulo') WHERE pe.nr_cep = '05338900';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Concórdia') WHERE pe.nr_cep = '89712060';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Uberlândia') WHERE pe.nr_cep = '38425627';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Tupaciguara') WHERE pe.nr_cep = '38480970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Aloândia') WHERE pe.nr_cep = '75619970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'São Paulo') WHERE pe.nr_cep = '05350901';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'São Paulo') WHERE pe.nr_cep = '04614905';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'São Paulo') WHERE pe.nr_cep = '05350901';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Caçador') WHERE pe.nr_cep = '89510000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Brasília') WHERE pe.nr_cep = '73270900';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Uberlândia') WHERE pe.nr_cep = '38425516';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Panamá') WHERE pe.nr_cep = '75599970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Nova Lima') WHERE pe.nr_cep = '34007970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Vila Velha') WHERE pe.nr_cep = '29100904';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Rio de Janeiro') WHERE pe.nr_cep = '20211903';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Vitória de Santo Antão') WHERE pe.nr_cep = '55612901';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Biguaçu') WHERE pe.nr_cep = '88162243';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Erechim') WHERE pe.nr_cep = '99708444';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Caçador') WHERE pe.nr_cep = '89510000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Magé') WHERE pe.nr_cep = '25931970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Concórdia') WHERE pe.nr_cep = '89712054';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Uberlândia') WHERE pe.nr_cep = '38425589';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Uberlândia') WHERE pe.nr_cep = '38425513';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Tupaciguara') WHERE pe.nr_cep = '38480000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'São Lourenço da Serra') WHERE pe.nr_cep = '06890970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Tupaciguara') WHERE pe.nr_cep = '38480000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Tupaciguara') WHERE pe.nr_cep = '38480000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Monte Alegre de Minas') WHERE pe.nr_cep = '38475000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Monte Alegre de Minas') WHERE pe.nr_cep = '38475000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Monte Alegre de Minas') WHERE pe.nr_cep = '38475000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Uberlândia') WHERE pe.nr_cep = '38425472';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Tupaciguara') WHERE pe.nr_cep = '38480000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Concórdia') WHERE pe.nr_cep = '89712060';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Panamá') WHERE pe.nr_cep = '75599970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Embu-Guaçu') WHERE pe.nr_cep = '06900070';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Miracema do Tocantins') WHERE pe.nr_cep = '77654970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Brasília') WHERE pe.nr_cep = '72445970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Concórdia') WHERE pe.nr_cep = '89712210';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Brasília') WHERE pe.nr_cep = '71215902';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'São Paulo') WHERE pe.nr_cep = '05145901';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Brasília') WHERE pe.nr_cep = '72115952';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'São Paulo') WHERE pe.nr_cep = '01221900';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'São Paulo') WHERE pe.nr_cep = '04523912';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Tupaciguara') WHERE pe.nr_cep = '38480970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Santo Antônio do Descoberto') WHERE pe.nr_cep = '72906494';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Franco da Rocha') WHERE pe.nr_cep = '07851970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Buriti Alegre') WHERE pe.nr_cep = '75664970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Panamá') WHERE pe.nr_cep = '75599970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Itapecerica da Serra') WHERE pe.nr_cep = '06886990';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Panamá') WHERE pe.nr_cep = '75599970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Biguaçu') WHERE pe.nr_cep = '88162243';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Erechim') WHERE pe.nr_cep = '99711400';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Itapecerica da Serra') WHERE pe.nr_cep = '06886990';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Tupaciguara') WHERE pe.nr_cep = '38480972';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Tupaciguara') WHERE pe.nr_cep = '38480000';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Brasília') WHERE pe.nr_cep = '71950904';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Nova Lima') WHERE pe.nr_cep = '34007970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Nova Lima') WHERE pe.nr_cep = '34007970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Rio Verde') WHERE pe.nr_cep = '75901970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Uberlândia') WHERE pe.nr_cep = '38425588';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Buriti Alegre') WHERE pe.nr_cep = '75664970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Brasília') WHERE pe.nr_cep = '72600970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Panamá') WHERE pe.nr_cep = '75599970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'Buriti Alegre') WHERE pe.nr_cep = '75664970';
UPDATE PESSOAENDERECO pe SET pe.cd_municipio = (SELECT m.cd_municipio FROM MUNICIPIO m WHERE m.nm_municipio = 'São Paulo') WHERE pe.nr_cep = '05872030';
